### ISSUE TITLE
Create a new repository

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/project-dadmin#34]
Command: `dadmin create repo -o <org> -r <regex> -d<local-directory> --is-private`

**Comment by snomos** [comment]
A variant of this would be to automatically create a remote repo for all local repos matching regex, and automatically set the remote origin at the same time.

Given local repos lang-A, lang-B, lang-C, stuff-D, the command

```
dadmin create repo -o <org> -r lang-.?
```

should create the remote repos lang-A, lang-B, lang-C (but *not* stuff-D), and set those as remote origin for the corresponding local repos.

**Comment by snomos** [comment]
There could also be an option to specify the root dir for the local repos, assuming that they are not part of the local `dadmin` root (yet).

**Comment by lenguyenthanh** [comment]
I think your variant is better. It'll look like this:
`dadmin create repo -o <org> -r <regex> -d<local-directory>`
The last option is optional, if it's not exist, dadmin will try to find local repos in `dadmin` root directory.

**Comment by snomos** [comment]
There also needs to be another option: `--private`, for repos that are going to be private.

When specified, it will apply to all repos created.

**Comment by lenguyenthanh** [comment]
Yeah, that's an important one.

Best,

Thanh
________________________________

**Comment by snomos** [comment]
> There also needs to be another option: `--private`, for repos that are going to be private.

This might imply a function to make a repo public, but I think those cases are so rare that we can deal with them manually using the GitHub web interface — I don't think we'll see massive changes of repos from private to public, since most repos will be public in the first place.

That is: not needed, and now also documented why I don't think we need a function to change a repo from private to public or the other way around.
