### ISSUE TITLE
Merge branch X with branch Y for all local repos [matching regex]

### ISSUE THREAD

**Issue by snomos** [divvun/project-dadmin#52]

**Comment by lenguyenthanh** [comment]
## Usage

`dadmin merge --base-branch <base-branch> --target-branch <target-branch> -o <org> -r <regex> --abort-if-confict`

## Effect

This command will try to merge target-branch into base-branch.
If flag `--abort-if-confict` is enable, this command will use `git commit --abort` command to abort if there is any unsolved conflict.
Otherwise it will leave repositories in the middle of the merge if there is any unsolved confilct
