### ISSUE TITLE
Add `--clone` option for create repo command

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/project-dadmin#62]
With this option, after creating all repositories on github, dadmin will copy all repositories to dadmin root directory.

**Comment by snomos** [comment]
Instead of copying, it could be a regular clone from remote origin, which would at the same time verify that the repo creation actually gave the result we want. It does involve network overhead and will be slower, but the added verification is possibly worth it.

Also, I think implementing it this way is faster and easier than doing a local disk copy, as the clone command is already in place.

**Comment by lenguyenthanh** [comment]
I agree, reuse clone command makes more senses.
